version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11.4-management-alpine
    container_name: 'rabbitmq'
    hostname: microservices_march
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - mm_2023

networks:
  mm_2023:
    name: mm_2023
    driver: bridge