---
version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11.4-management-alpine
    container_name: "rabbitmq"
    hostname: microservices_march
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq/
      - rabbit-log:/var/log/rabbitmq/
    networks:
      - mm_2023

  consul-server:
    image: hashicorp/consul:1.14.4
    container_name: consul-server
    restart: always
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
    networks:
      - mm_2023
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"
    networks:
      - mm_2023
  
  consul-client:
    image: hashicorp/consul:1.14.4
    container_name: consul-client
    restart: always
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
    networks:
      - mm_2023
    command: "agent"
    networks:
      - mm_2023

  # collector:
  #   image: otel/opentelemetry-collector:latest
  #   container_name: collector
  #   depends_on:
  #     - jaeger
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   volumes:
  #     - ./otel_collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   networks:
  #     - mm_2023

  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger_1
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - mm_2023


volumes:
  rabbit-data:
  rabbit-log:

networks:
  mm_2023:
    name: mm_2023
    driver: bridge
